image: maven:latest

stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build template:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test template:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

package template:
  stage: package
  script:
  - mvn $MAVEN_CLI_OPTS package
  artifacts:
    name: "$CI_JOB_NAME"
    when: on_success
    paths:
    - target/*.jar