---
- name: Install Docker
  hosts: all
  remote_user: bram
  become: yes
  tasks:
    - name: Install Docker requirements
      apt: name={{item}} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} nightly
    - name: Install Docker
      apt: name=docker-ce update_cache=yes
- name: Deploy Project
  hosts: all
  remote_user: bram
  become: yes
  tasks:
    - name: Copy WAR file
      copy:
        src: target/*.war
        dest: /webapp/
        owner: bram
        group: bram
        mode: 0750
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /webapp/docker-compose.yml
        owner: bram
        group: bram
        mode: 0750
    - name: Build the docker images
      docker_service:
        project_name: Web App
        project_src: /webapp
        build: yes
    - name: Start the web app
      docker_service:
        project_name: Web App
        project_src: /webapp
        state: present



